#!/usr/bin/env python3
"""Stage 11: build a named-view mirror of the decompiled output.

Ghidra's exports under build/decomp/<prog>/ (decompiled.c + functions.tsv) are
treated as read-only derived artifacts: they are byte-identical to what stage 07
wrote and are never edited. This stage copies them into build/named/<prog>/ and
applies the curated name map config/ghidra/rename-map.json (word-boundary
substitutions), so the named view is a separate derived copy that `make clean`
regenerates like everything else.

The map keys are image-relative addresses for the flat image:
  globals   0x16d6c -> g_mode_flag      (renames DAT_00016d6c)
  functions 0x5bada -> rng_next         (renames FUN_0005bada)
  literals  0xc3f4  -> g_obj_list_sentinel  (renames the raw literal 0xc3f4)
Global keys also rename RAM-pointer symbols: iRam0000c3c4 and uRam0000c3c4
are matched for globals such as 0xc3c4 -> g_galaxy_ptr.
Hex keys may be written with or without the 0x prefix, any case. Names must be
valid C identifiers (the script refuses to apply anything else).

The named view is derived game code and lives only under build/ (gitignored).
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import openfa_lib as lib  # noqa: E402

MAP_FILE = lib.ROOT / "config" / "ghidra" / "rename-map.json"

_IDENT = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
_HEX = set("0123456789abcdef")


def load_map(path: Path) -> tuple[list[tuple[str, str]], int]:
    """Return ([old_token -> new_name], applied_map_size)."""
    if not path.exists():
        return [], 0
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"{path}: expected a JSON object")

    tables: list[tuple[str, str]] = []

    def add_global(kind: str, prefix: str) -> None:
        for raw, name in (data.get(kind) or {}).items():
            addr = raw.strip().lower()
            if addr.startswith("0x"):
                addr = addr[2:]
            if not addr or not all(c in _HEX for c in addr):
                raise ValueError(f"invalid {kind} address {raw!r} in {path}")
            if not _IDENT.match(name):
                raise ValueError(f"not a valid C identifier {name!r} in {path}")
            token = f"{prefix}{int(addr, 16):08x}"
            # Ghidra prefixes overlapping globals with '_' (_DAT_0006bfb8).
            for t in (token, f"_{token}"):
                if t not in dict(tables):
                    tables.append((t, name))

    add_global("globals", "DAT_")
    # RAM-pointer globals get iRam/uRam symbols rather than DAT_.
    add_global("globals", "iRam")
    add_global("globals", "uRam")
    add_global("functions", "FUN_")

    for raw, name in (data.get("literals") or {}).items():
        addr = raw.strip().lower()
        if addr.startswith("0x"):
            addr = addr[2:]
        if not addr or not all(c in _HEX for c in addr):
            raise ValueError(f"invalid literal address {raw!r} in {path}")
        if not _IDENT.match(name):
            raise ValueError(f"not a valid C identifier {name!r} in {path}")
        tables.append((f"0x{int(addr, 16):x}", name))

    # longest first so a token is never a prefix of a longer one being replaced
    tables.sort(key=lambda kv: len(kv[0]), reverse=True)
    return tables, len(data.get("globals", {})) + len(data.get("functions", {})) \
        + len(data.get("literals", {}))


def _subst(text: str, tables: list[tuple[str, str]]) -> str:
    for old, new in tables:
        text = re.sub(rf"\b{re.escape(old)}\b", new, text)
    return text


def header(program: str, applied: int, mapped: int) -> str:
    return (
        f"/* Named view of build/decomp/{program}/decompiled.c.\n"
        f" * Generated by scripts/11_apply_names.py from\n"
        f" * config/ghidra/rename-map.json ({mapped} curated name(s), {applied}\n"
        f" * token(s) matched here). The raw export in build/decomp/ is untouched.\n"
        f" * This is derived game code; it stays under build/ (gitignored). */\n\n"
    )


def process_program(prog_dir: Path, out_dir: Path, tables: list[tuple[str, str]],
                    mapped: int) -> int:
    src_c = prog_dir / "decompiled.c"
    if not src_c.exists():
        return 0
    out_dir.mkdir(parents=True, exist_ok=True)

    text = src_c.read_text(encoding="utf-8")
    named = _subst(text, tables)
    applied = sum(old in text for old, _ in tables)
    (out_dir / "decompiled.c").write_text(header(prog_dir.name, applied, mapped)
                                          + named, encoding="utf-8")

    src_t = prog_dir / "functions.tsv"
    if src_t.exists():
        rows = src_t.read_text(encoding="utf-8").splitlines()
        named_rows = []
        for line in rows:
            name, sep, rest = line.partition("\t")
            named_rows.append(_subst(name, tables) + sep + rest if sep else line)
        (out_dir / "functions.tsv").write_text("\n".join(named_rows) + "\n",
                                               encoding="utf-8")
    return 1


def main() -> int:
    cfg = lib.load_config()
    decomp = lib.decomp_dir(cfg)
    outroot = lib.named_dir(cfg)
    tables, mapped = load_map(MAP_FILE)

    programs = [p for p in sorted(decomp.iterdir())
                if p.is_dir() and (p / "decompiled.c").exists()]
    if not programs:
        lib.note(f"no decompiled output under {decomp}; run `make disassemble` "
                 "first", "yellow")
        return 0
    count = sum(process_program(p, outroot / p.name, tables, mapped)
                for p in programs)
    lib.note(f"[apply_names] {mapped} name(s) from {MAP_FILE}; "
             f"{count} program(s) mirrored to {outroot}", "green")
    return 0


if __name__ == "__main__":
    sys.exit(main())
